---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/employee":
    get:
      summary: list employees
      tags:
      - Employees
      responses:
        '200':
          description: successful
    post:
      summary: create employee
      tags:
      - Employees
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: Body parametrs
        '422':
          description: Validation data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                family_name:
                  type: string
                birthday_date:
                  type: string
                  format: date
                hiring_date:
                  type: string
                  format: date
                photo_profile:
                  type: string
                net_salary:
                  type: number
                  format: float
              required:
              - name
              - family_name
  "/v1/employee/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update employee
      tags:
      - Employees
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: Employee not found
        '400':
          description: Body parametrs
        '403':
          description: Missing Required Parametrs
        '422':
          description: Validation data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                family_name:
                  type: string
                birthday_date:
                  type: string
                  format: date
                hiring_date:
                  type: string
                  format: date
                photo_profile:
                  type: string
                net_salary:
                  type: number
                  format: float
    put:
      summary: update employee
      tags:
      - Employees
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: Employee not found
        '400':
          description: Body parametrs
        '403':
          description: Missing Required Parametrs
        '422':
          description: Validation data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                family_name:
                  type: string
                birthday_date:
                  type: string
                  format: date
                hiring_date:
                  type: string
                  format: date
                photo_profile:
                  type: string
                net_salary:
                  type: number
                  format: float
    delete:
      summary: delete employee
      tags:
      - Employees
      responses:
        '200':
          description: successful
        '404':
          description: Employee not found
        '422':
          description: Validation data
  "/v1/session":
    post:
      summary: create session
      tags:
      - Session
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/v1/user":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: body parametrs
        '422':
          description: validation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
                employee_id:
                  type: integer
              required:
              - username
              - password
              - role
              - employee_id
  "/v1/user/{id}":
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    patch:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: User not found
        '400':
          description: Body parametrs
        '401':
          description: Missing parametrs
        '422':
          description: Validation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
    put:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: User not found
        '400':
          description: Body parametrs
        '401':
          description: Missing parametrs
        '422':
          description: Validation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
    delete:
      summary: delete user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: User not found
        '422':
          description: Validation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: bodor-human-ressources-backend.herokuapp.com/
