---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/user":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
        '422':
          description: users not found
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: body parametrs
        '403':
          description: database validation and processing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Full_name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
              - Full_name
              - username
              - password
              - role
  "/v1/user/{id}":
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    - name: user
      in: body
      schema:
        type: object
        properties:
          Full_name:
            type: string
          username:
            type: string
          password:
            type: string
          role:
            type: string
    patch:
      summary: update user
      tags:
      - Users
      responses:
        '200':
          description: successful
        '404':
          description: user not found
        '422':
          description: database validation and processing
    put:
      summary: update user
      tags:
      - Users
      responses:
        '200':
          description: successful
        '404':
          description: user not found
        '422':
          description: database validation and processing
    delete:
      summary: delete user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
